[package]
name = "campus_dao"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
soroban-sdk = "20.0.0"

[dev-dependencies]
soroban-sdk = { version = "20.0.0", features = ["testutils"] }

[features]
testutils = []


[profile.release]
lto = true
opt-level = 's'
panic = 'abort'
codegen-units = 1